services:
  chains:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:admin@db/postgres
      - DISCORD_TOKEN=OTQ5MTAxMzgyNDcwODY5MDUy.YiFdiw.RyG2Fzp21dAHulHBL5jjkBkK_bM
      - DISCORD_PREFIX=>
      - COMPOSE_PROJECT_NAME=chains
    links:
      - "db:database"
  db:
    build: ./db/
    ports:
     - "5432:5432"
    environment:
      - COMPOSE_PROJECT_NAME=db
